// This file is auto-generated by @hey-api/openapi-ts

export const $User = {
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
      description: "ไอดีของผู้ใช้งาน",
      example: "123e4567-e89b-12d3-a456-426614174000",
    },
    email: {
      type: "string",
      format: "email",
      description: "อีเมลของผู้ใช้งาน",
      example: "user@example.com",
    },
    firstName: {
      type: "string",
      description: "ชื่อต้นของผู้ใช้งาน",
      example: "John",
    },
    lastName: {
      type: "string",
      description: "นามสกุลของผู้ใช้งาน",
      example: "Doe",
    },
    roles: {
      type: "array",
      items: {
        type: "string",
      },
      description: "บทบาทของผู้ใช้งาน",
      example: ["user"],
    },
    isActive: {
      type: "boolean",
      description: "สถานะการใช้งาน",
      example: true,
    },
    createdAt: {
      type: "string",
      nullable: true,
      description: "วันและเวลาที่สร้างผู้ใช้งาน",
      example: "2026-01-01T00:00:00Z",
    },
    updatedAt: {
      type: "string",
      nullable: true,
      description: "วันและเวลาที่อัปเดตข้อมูลผู้ใช้งานล่าสุด",
      example: "2026-01-01T00:00:00Z",
    },
    verifiedAt: {
      type: "string",
      nullable: true,
      description: "วันและเวลาที่ยืนยันอีเมล",
      example: null,
    },
    acceptTermOfUseAt: {
      type: "string",
      nullable: true,
      description: "วันและเวลาที่ยอมรับข้อตกลงการใช้งาน",
      example: null,
    },
    dob: {
      type: "string",
      nullable: true,
      description: "วันเกิด",
      example: "1990-01-01",
    },
    gender: {
      type: "string",
      nullable: true,
      description: "เพศ",
      example: "male",
    },
    phone: {
      type: "string",
      nullable: true,
      description: "เบอร์โทรศัพท์",
      example: "+1234567890",
    },
    personalInfo: {
      type: "object",
      nullable: true,
      properties: {
        age: {
          type: "integer",
          minimum: 0,
          maximum: 150,
        },
        addressLine: {
          type: "string",
        },
        street: {
          type: "string",
        },
        subdistrict: {
          type: "string",
        },
        district: {
          type: "string",
        },
        province: {
          type: "string",
        },
        postalCode: {
          type: "string",
        },
        phone: {
          type: "string",
        },
      },
      description: "ข้อมูลส่วนตัว",
    },
    sirirajInfoSheetConsentAt: {
      type: "string",
      nullable: true,
      description: "วันที่ยินยอมเอกสาร Participant Information Sheet",
    },
    sirirajConsentAt: {
      type: "string",
      nullable: true,
      description: "วันที่ยินยอม Siriraj",
    },
    sirirajQuestionnaireSubmitted: {
      type: "boolean",
      description: "true ถ้าผู้ใช้ส่งแบบสอบถาม Siriraj แล้ว",
    },
  },
  required: [
    "id",
    "email",
    "firstName",
    "lastName",
    "roles",
    "isActive",
    "createdAt",
    "updatedAt",
    "verifiedAt",
    "acceptTermOfUseAt",
  ],
  description: "ข้อมูลของผู้ใช้งานในระบบ",
  example: {
    id: "123e4567-e89b-12d3-a456-426614174000",
    email: "user@example.com",
    firstName: "John",
    lastName: "Doe",
    roles: ["user"],
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    verifiedAt: null,
    acceptTermOfUseAt: null,
    dob: "1990-01-01",
    gender: "male",
    phone: "+1234567890",
  },
} as const;

export const $UserSetting = {
  type: "object",
  properties: {
    id: {
      type: "string",
      description: "ไอดีของการตั้งค่า",
      example: "",
    },
    userId: {
      type: "string",
      format: "uuid",
      description: "ไอดีของผู้ใช้งาน",
      example: "123e4567-e89b-12d3-a456-426614174000",
    },
    enableEmailNotification: {
      type: "boolean",
      description: "สถานะการแจ้งเตือนอีเมล",
      example: true,
    },
    updatedAt: {
      type: "string",
      description: "วันและเวลาที่อัปเดตข้อมูลล่าสุด",
      example: "2023-01-01T00:00:00Z",
    },
  },
  required: ["id", "userId", "enableEmailNotification", "updatedAt"],
  description: "การตั้งค่าการแจ้งเตือนสำหรับผู้ใช้งาน",
  example: {
    id: "",
    userId: "123e4567-e89b-12d3-a456-426614174000",
    enableEmailNotification: true,
    updatedAt: "",
  },
} as const;

export const $AIChatConversation = {
  type: "object",
  properties: {
    event: {
      type: "string",
      description: "ประเภทเหตุการณ์",
      example: "event type",
    },
    data: {
      type: "string",
      description:
        "ข้อมูลที่ส่งผ่านเหตุการณ์ในรูปแบบของสตริงหรือออปเจ็กต์ JSON",
      example: "event payload",
    },
    id: {
      type: "string",
      description: "ตัวระบุเฉพาะสำหรับเหตุการณ์",
      example: "event id",
    },
    retry: {
      type: "number",
      description:
        "ระยะเวลาหน่วงในการเชื่อมต่อใหม่ (หน่วยเป็นมิลลิวินาที) หากการเชื่อมต่อขาดหายไป",
      example: 3000,
    },
  },
  required: ["data"],
} as const;

export const $ChatRoom = {
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
      description: "ไอดีของห้องสนทนา",
      example: "123e4567-e89b-12d3-a456-426614174000",
    },
    title: {
      type: "string",
      description: "ชื่อของห้องสนทนา",
      example: "My Chat Room",
    },
    description: {
      type: "string",
      nullable: true,
      description: "รายละเอียดของห้องสนทนา",
      example: "A chat about health",
    },
    userId: {
      type: "string",
      format: "uuid",
      description: "ไอดีของผู้ใช้",
      example: "123e4567-e89b-12d3-a456-426614174000",
    },
    createdAt: {
      type: "string",
      description: "วันและเวลาที่สร้าง",
      example: "2024-01-01T00:00:00Z",
    },
    updatedAt: {
      type: "string",
      description: "วันและเวลาที่อัปเดตล่าสุด",
      example: "2024-01-01T00:00:00Z",
    },
  },
  required: ["id", "title", "userId", "createdAt", "updatedAt"],
} as const;

export const $ChatRoomsResponse = {
  type: "array",
  items: {
    $ref: "#/components/schemas/ChatRoom",
  },
} as const;

export const $PendingToolCall = {
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
      description: "ไอดีของ pending tool call",
      example: "123e4567-e89b-12d3-a456-426614174000",
    },
    toolName: {
      type: "string",
      description: "ชื่อของ tool ที่รอดำเนินการ",
      example: "add-medical-reminder",
    },
    toolArgs: {
      type: "object",
      additionalProperties: {
        nullable: true,
      },
      description: "อาร์กิวเมนต์ของ tool",
    },
    chatroomId: {
      type: "string",
      nullable: true,
      format: "uuid",
      description: "ไอดีของห้องสนทนา",
      example: "123e4567-e89b-12d3-a456-426614174000",
    },
    status: {
      type: "string",
      description: "สถานะของ pending tool call",
      example: "pending",
    },
    createdAt: {
      type: "string",
      description: "วันและเวลาที่สร้าง",
      example: "2024-01-01T00:00:00Z",
    },
  },
  required: ["id", "toolName", "toolArgs", "chatroomId", "status", "createdAt"],
} as const;

export const $PendingToolCallsResponse = {
  type: "array",
  items: {
    $ref: "#/components/schemas/PendingToolCall",
  },
} as const;

export const $ChatConversation = {
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
      description: "ไอดีของการสนทนา",
      example: "123e4567-e89b-12d3-a456-426614174000",
    },
    chatroomId: {
      type: "string",
      format: "uuid",
      description: "ไอดีของห้องสนทนา",
      example: "123e4567-e89b-12d3-a456-426614174000",
    },
    role: {
      type: "string",
      description: "บทบาทของผู้ใช้",
      example: "user",
    },
    content: {
      type: "string",
      description: "เนื้อหาของการสนทนา",
      example: "Hello, how are you?",
    },
    actionType: {
      type: "string",
      nullable: true,
      description: "ประเภทการปฏิบัติ",
      example: "choice",
    },
    choices: {
      type: "array",
      nullable: true,
      items: {
        type: "string",
      },
      description: "รายการทางเลือก",
      example: ["Option 1", "Option 2"],
    },
    selectedChoices: {
      type: "array",
      nullable: true,
      items: {
        type: "string",
      },
      description: "รายการทางเลือกที่เลือก",
      example: ["Option 1"],
    },
    options: {
      type: "array",
      nullable: true,
      items: {
        type: "object",
        properties: {
          label: {
            type: "string",
          },
          value: {
            type: "string",
          },
        },
        required: ["label"],
      },
      description: "รายการตัวเลือก",
      example: [
        {
          label: "Yes",
          value: "yes",
        },
      ],
    },
    disabled: {
      type: "boolean",
      description: "สถานะการปิดใช้งาน",
      example: false,
    },
    title: {
      type: "string",
      nullable: true,
      description: "ชื่อของการสนทนา",
      example: "Message Title",
    },
    hasInput: {
      type: "boolean",
      description: "สถานะการใช้อินพุต",
      example: false,
    },
    responseToConversationId: {
      type: "string",
      nullable: true,
      format: "uuid",
      description: "ไอดีของการสนทนาที่ตอบกลับ",
      example: "123e4567-e89b-12d3-a456-426614174000",
    },
    category: {
      type: "string",
      nullable: true,
      description: "ประเภทของการสนทนา",
      example: "medical_advice",
    },
    toolCalls: {
      type: "array",
      nullable: true,
      items: {
        type: "object",
        properties: {
          id: {
            type: "string",
          },
          type: {
            type: "string",
            enum: ["function"],
          },
          function: {
            type: "object",
            properties: {
              name: {
                type: "string",
              },
              arguments: {
                type: "string",
              },
            },
            required: ["name", "arguments"],
          },
        },
        required: ["id", "type", "function"],
      },
      description: "Tool calls made by the assistant",
      example: [
        {
          id: "call_123",
          type: "function",
          function: {
            name: "search_medical_facts",
            arguments: "{}",
          },
        },
      ],
    },
    metadata: {
      type: "object",
      nullable: true,
      additionalProperties: {
        nullable: true,
      },
      description: "Additional metadata for the conversation",
    },
    createdAt: {
      type: "string",
      description: "วันและเวลาที่สร้าง",
      example: "2024-01-01T00:00:00Z",
    },
  },
  required: [
    "id",
    "chatroomId",
    "role",
    "content",
    "disabled",
    "hasInput",
    "createdAt",
  ],
} as const;

export const $ChatConversationsResponse = {
  type: "array",
  items: {
    $ref: "#/components/schemas/ChatConversation",
  },
} as const;

export const $SuccessResponse = {
  type: "object",
  properties: {
    success: {
      type: "boolean",
      description: "สถานะการสำเร็จ",
      example: true,
    },
    message: {
      type: "string",
      description: "ข้อความแสดงผล",
      example: "Operation completed successfully",
    },
  },
  required: ["success"],
} as const;

export const $ApiKey = {
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
      description: "ไอดีของ API key",
      example: "1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
    },
    userId: {
      type: "string",
      format: "uuid",
      description: "ไอดีของผู้ใช้งาน",
      example: "1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
    },
    name: {
      type: "string",
      description: "ชื่อ API key",
      example: "API Key Name",
    },
    apiKey: {
      type: "string",
      description: "API key",
      example: "1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
    },
    isActivated: {
      type: "boolean",
      description: "สถานะการใช้งาน",
      example: true,
    },
    usageLimit: {
      type: "number",
      nullable: true,
      description: "จำกัดจำนวนการใช้งาน",
      example: 100,
    },
    limitPeriod: {
      type: "string",
      nullable: true,
      enum: ["day", "month"],
      description: "ระยะเวลาการใช้งาน",
      example: "day",
    },
    currentUsage: {
      type: "number",
      description: "จำนวนการใช้งานปัจจุบัน",
      example: 50,
    },
    createdAt: {
      type: "string",
      description: "วันและเวลาที่สร้าง API key",
      example: "2023-01-01T00:00:00Z",
    },
    updatedAt: {
      type: "string",
      description: "วันและเวลาที่อัปเดตข้อมูล API keyล่าสุด",
      example: "2023-01-01T00:00:00Z",
    },
  },
  required: [
    "id",
    "userId",
    "name",
    "apiKey",
    "isActivated",
    "currentUsage",
    "createdAt",
    "updatedAt",
  ],
} as const;

export const $GetSubscriptionsResponse = {
  type: "object",
  properties: {
    subscriptions: {
      type: "number",
      description: "จำนวนการสมัครรับการแจ้งเตือนแบบพุช",
      example: 1,
    },
    endpoints: {
      type: "array",
      items: {
        type: "string",
      },
      description: "URL ของปลายทาง",
      example: ["https://fcm.googleapis.com/fcm/send/..."],
    },
  },
  required: ["subscriptions", "endpoints"],
  description: "การตอบกลับรายการการสมัครรับการแจ้งเตือนแบบพุช",
} as const;

export const $ErrorResponse = {
  type: "object",
  properties: {
    error: {
      type: "string",
      description: "ข้อความอธิบายข้อผิดพลาด",
      example: "Bad request",
    },
    timestamp: {
      type: "string",
      description: "เวลาปัจจุบันตามมาตรฐาน ISO 8601",
      example: "2023-01-01T00:00:00Z",
    },
  },
  required: ["error", "timestamp"],
  description: "ข้อผิดพลาด",
} as const;

export const $SubscribeResponse = {
  type: "object",
  properties: {
    success: {
      type: "boolean",
      description: "สถานะการสมัคร",
      example: true,
    },
    message: {
      type: "string",
      description: "ข้อความแสดงผลเมื่อสมัครสำเร็จ",
      example: "Subscription successful",
    },
  },
  required: ["success", "message"],
  description: "การตอบกลับการสมัครรับการแจ้งเตือนแบบพุช",
} as const;

export const $UnsubscribeResponse = {
  type: "object",
  properties: {
    success: {
      type: "boolean",
      description: "สถานะการยกเลิก",
      example: true,
    },
    message: {
      type: "string",
      description: "ข้อความแสดงผลเมื่อยกเลิกสำเร็จ",
      example: "Unsubscription successful",
    },
  },
  required: ["success", "message"],
  description: "การตอบกลับการยกเลิกการรับการแจ้งเตือนแบบพุช",
} as const;
