// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise";
import { OpenAPI } from "./core/OpenAPI";
import { request as __request } from "./core/request";
import type {
  GetHealthResponse,
  PostAuthLoginData,
  PostAuthLoginResponse,
  PostAuthRegisterData,
  PostAuthRegisterResponse,
  PostAuthSendVerificationEmailData,
  PostAuthSendVerificationEmailResponse,
  GetVerifyEmailData,
  PostAuthRefreshData,
  PostAuthRefreshResponse,
  PostAuthLogoutResponse,
  PostAuthForgetPasswordData,
  PostAuthForgetPasswordResponse,
  PostAuthResetPasswordData,
  PostAuthResetPasswordResponse,
  GetAuthMeResponse,
  PostUsersByIdAcceptTermsData,
  PostUsersByIdAcceptTermsResponse,
  GetUsersSettingResponse,
  PutUsersSettingData,
  PutUsersSettingResponse,
  DeleteUsersByIdData,
  DeleteUsersByIdResponse,
  PutUsersByIdData,
  PutUsersByIdResponse,
  GetUsersData,
  GetUsersResponse,
  PostUsersByIdSetActiveData,
  PostUsersByIdSetActiveResponse,
  PostUsersByIdSetRolesData,
  PostUsersByIdSetRolesResponse,
  GetAppointmentsPrescreenResultsResponse,
  GetAppointmentsPrescreenPrefillResponse,
  GetAppointmentsHospitalsResponse,
  GetAppointmentsData,
  GetAppointmentsResponse,
  PostAppointmentsData,
  PostAppointmentsResponse,
  GetAppointmentsByIdData,
  GetAppointmentsByIdResponse,
  PutAppointmentsByIdData,
  PutAppointmentsByIdResponse,
  DeleteAppointmentsByIdData,
  DeleteAppointmentsByIdResponse,
  GetLlmaasAppointmentsData,
  GetLlmaasAppointmentsResponse,
  PostLlmaasAppointmentsData,
  PostLlmaasAppointmentsResponse,
  PostLlmaasChatData,
  PostLlmaasChatResponse,
  PostChatAiToolResponseData,
  PostChatAiToolResponseResponse,
  PostChatAiData,
  PostChatAiResponse,
  PostChatRoomsData,
  PostChatRoomsResponse,
  GetChatRoomsResponse,
  GetChatRoomsByIdPendingToolCallsData,
  GetChatRoomsByIdPendingToolCallsResponse,
  GetChatRoomsByIdConversationsData,
  GetChatRoomsByIdConversationsResponse,
  PutChatConversationsData,
  PutChatConversationsResponse,
  DeleteChatRoomsByIdData,
  DeleteChatRoomsByIdResponse,
  GetChatConversationStatsData,
  GetChatConversationStatsResponse,
  GetArenaModelsResponse,
  PostArenaAskData,
  PostArenaAskResponse,
  PostArenaVoteData,
  PostArenaVoteResponse,
  PostArenaRetryData,
  PostArenaRetryResponse,
  GetArenaExportResponse,
  GetArenaStatsResponse,
  GetArenaAdminModelsResponse,
  PostArenaAdminModelsData,
  PostArenaAdminModelsResponse,
  PutArenaAdminModelsByIdData,
  PutArenaAdminModelsByIdResponse,
  DeleteArenaAdminModelsByIdData,
  DeleteArenaAdminModelsByIdResponse,
  PostArenaAdminModelsTestData,
  PostArenaAdminModelsTestResponse,
  PostMedicalRemindersResponseData,
  PostMedicalRemindersResponseResponse,
  GetMedicalRemindersSchedulesHistoryResponse,
  GetMedicalRemindersSchedulesUpcomingResponse,
  GetMedicalRemindersSchedulesResponse,
  PostMedicalRemindersSchedulesData,
  PostMedicalRemindersSchedulesResponse,
  GetMedicalRemindersSchedulesByIdData,
  GetMedicalRemindersSchedulesByIdResponse,
  PutMedicalRemindersSchedulesByIdData,
  PutMedicalRemindersSchedulesByIdResponse,
  DeleteMedicalRemindersSchedulesByIdData,
  DeleteMedicalRemindersSchedulesByIdResponse,
  GetApiKeysData,
  GetApiKeysResponse,
  PostApiKeysData,
  PostApiKeysResponse,
  GetApiKeysByIdData,
  GetApiKeysByIdResponse,
  PutApiKeysByIdData,
  PutApiKeysByIdResponse,
  DeleteApiKeysByIdData,
  DeleteApiKeysByIdResponse,
  PostApiKeysByIdRegenerateData,
  PostApiKeysByIdRegenerateResponse,
  GetApiPushSubscribeResponse,
  PostApiPushSubscribeData,
  PostApiPushSubscribeResponse,
  DeleteApiPushSubscribeByEndpointData,
  DeleteApiPushSubscribeByEndpointResponse,
  GetAdminCronStatusResponse,
  PostAdminCronCleanupSessionsResponse,
  PostAdminCronStartTaskData,
  PostAdminCronStartTaskResponse,
  PostAdminCronStopTaskData,
  PostAdminCronStopTaskResponse,
  PostAdminCronExecuteTaskData,
  PostAdminCronExecuteTaskResponse,
} from "./types.gen";

/**
 * ตรวจสอบสถานะของแอปพลิเคชัน
 * ตอบกลับสถานะของแอปพลิเคชันรวมถึงระยะเวลาที่ระบบทำงานต่อเนื่อง (uptime) และเวลาปัจจุบัน ณ ขณะนั้น (timestamp)
 * @returns unknown Health status retrieved successfully
 * @throws ApiError
 */
export const getHealth = (): CancelablePromise<GetHealthResponse> => {
  return __request(OpenAPI, {
    method: "GET",
    url: "/health",
    errors: {
      500: "Internal server error",
    },
  });
};

/**
 * ยืนยันตัวตนของผู้ใช้งานด้วยอีเมลและรหัสผ่าน
 * ยืนยันตัวตนของผู้ใช้งานด้วยอีเมลและรหัสผ่าน
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Login successful
 * @throws ApiError
 */
export const postAuthLogin = (
  data: PostAuthLoginData = {},
): CancelablePromise<PostAuthLoginResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/auth/login",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      401: "Invalid credentials",
      409: "Conflict - validation error",
      500: "Internal server error",
    },
  });
};

/**
 * สร้างบัญชีผู้ใช้งานด้วยอีเมลและรหัสผ่าน
 * สร้างบัญชีผู้ใช้งานด้วยอีเมลและรหัสผ่าน
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown User registered successfully
 * @throws ApiError
 */
export const postAuthRegister = (
  data: PostAuthRegisterData = {},
): CancelablePromise<PostAuthRegisterResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/auth/register",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      400: "Bad request - validation errors",
      409: "Conflict - user already exists",
      500: "Internal server error",
    },
  });
};

/**
 * ส่งอีเมลยืนยันตัวตนให้ผู้ใช้งาน
 * ส่งอีเมลยืนยันตัวตนให้ผู้ใช้งาน
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Verification email sent
 * @throws ApiError
 */
export const postAuthSendVerificationEmail = (
  data: PostAuthSendVerificationEmailData = {},
): CancelablePromise<PostAuthSendVerificationEmailResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/auth/send-verification-email",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      400: "Bad request - missing email",
      401: "Unauthorized - user not found",
      500: "Internal server error",
    },
  });
};

/**
 * ยืนยันอีเมลของผู้ใช้งานด้วยโทเคน
 * ยืนยันอีเมลของผู้ใช้งานด้วยโทเคน
 * @param data The data for the request.
 * @param data.token
 * @throws ApiError
 */
export const getVerifyEmail = (
  data: GetVerifyEmailData,
): CancelablePromise<void> => {
  return __request(OpenAPI, {
    method: "GET",
    url: "/verify-email",
    query: {
      token: data.token,
    },
    errors: {
      302: "Redirect to callback URL after verification",
      400: "Bad request - missing or invalid token",
      401: "Unauthorized - invalid or expired token",
      500: "Internal server error",
    },
  });
};

/**
 * รับโทเคนการเข้าถึงด้วยโทเคนรีเฟรช
 * รับโทเคนการเข้าถึงด้วยโทเคนรีเฟรช
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Token refreshed successfully
 * @throws ApiError
 */
export const postAuthRefresh = (
  data: PostAuthRefreshData = {},
): CancelablePromise<PostAuthRefreshResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/auth/refresh",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      400: "Bad request - missing refresh token",
      401: "Unauthorized - invalid refresh token",
      500: "Internal server error",
    },
  });
};

/**
 * ลงชื่อผู้ใช้งานออกจากระบบ
 * ลงชื่อผู้ใช้งานออกจากระบบและลบโทเคนการเข้าถึง
 * @returns unknown Logout successful
 * @throws ApiError
 */
export const postAuthLogout = (): CancelablePromise<PostAuthLogoutResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/auth/logout",
    errors: {
      400: "Bad request - missing token",
      401: "Unauthorized - missing or invalid token",
      500: "Internal server error",
    },
  });
};

/**
 * ส่งคำขอรีเซ็ตรหัสผ่านสำหรับผู้ใช้งาน
 * ส่งคำขอรีเซ็ตรหัสผ่านสำหรับผู้ใช้งาน
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Password reset email sent
 * @throws ApiError
 */
export const postAuthForgetPassword = (
  data: PostAuthForgetPasswordData = {},
): CancelablePromise<PostAuthForgetPasswordResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/auth/forget-password",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      400: "Bad request - missing email",
      401: "Unauthorized - user not found",
      500: "Internal server error",
    },
  });
};

/**
 * รีเซ็ตรหัสผ่านสำหรับผู้ใช้งาน
 * รีเซ็ตรหัสผ่านสำหรับผู้ใช้งาน
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Password reset successfully
 * @throws ApiError
 */
export const postAuthResetPassword = (
  data: PostAuthResetPasswordData = {},
): CancelablePromise<PostAuthResetPasswordResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/auth/reset-password",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      400: "Bad request - missing or invalid token/password",
      401: "Unauthorized - invalid or expired token",
      500: "Internal server error",
    },
  });
};

/**
 * รับข้อมูลโปรไฟล์ผู้ใช้งาน
 * รับข้อมูลโปรไฟล์ผู้ใช้งานด้วยโทเคนเซสชัน
 * @returns unknown Profile retrieved successfully
 * @throws ApiError
 */
export const getAuthMe = (): CancelablePromise<GetAuthMeResponse> => {
  return __request(OpenAPI, {
    method: "GET",
    url: "/auth/me",
    errors: {
      401: "Unauthorized - missing or invalid token",
      500: "Internal server error",
    },
  });
};

/**
 * ยอมรับข้อตกลงการใช้งาน
 * ยอมรับข้อตกลงการใช้งาน
 * @param data The data for the request.
 * @param data.id
 * @returns User Terms accepted successfully
 * @throws ApiError
 */
export const postUsersByIdAcceptTerms = (
  data: PostUsersByIdAcceptTermsData,
): CancelablePromise<PostUsersByIdAcceptTermsResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/users/{id}/accept-terms",
    path: {
      id: data.id,
    },
    errors: {
      404: "User not found",
      500: "Internal server error",
    },
  });
};

/**
 * รับข้อมูลการตั้งค่าการแจ้งเตือนสำหรับผู้ใช้งาน
 * รับข้อมูลการตั้งค่าการแจ้งเตือนสำหรับผู้ใช้งาน
 * @returns UserSetting User settings fetched successfully
 * @throws ApiError
 */
export const getUsersSetting =
  (): CancelablePromise<GetUsersSettingResponse> => {
    return __request(OpenAPI, {
      method: "GET",
      url: "/users/setting",
      errors: {
        401: "Unauthorized",
        404: "User not found",
        500: "Internal server error",
      },
    });
  };

/**
 * สร้างหรืออัปเดตข้อมูลการตั้งค่าการแจ้งเตือนสำหรับผู้ใช้งาน
 * สร้างหรืออัปเดตข้อมูลการตั้งค่าการแจ้งเตือนสำหรับผู้ใช้งาน
 * @param data The data for the request.
 * @param data.requestBody
 * @returns UserSetting User settings upserted successfully
 * @throws ApiError
 */
export const putUsersSetting = (
  data: PutUsersSettingData = {},
): CancelablePromise<PutUsersSettingResponse> => {
  return __request(OpenAPI, {
    method: "PUT",
    url: "/users/setting",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      401: "Unauthorized",
      404: "User not found",
      500: "Internal server error",
    },
  });
};

/**
 * ลบผู้ใช้งาน
 * ลบผู้ใช้งาน
 * @param data The data for the request.
 * @param data.id
 * @returns unknown User deleted successfully
 * @throws ApiError
 */
export const deleteUsersById = (
  data: DeleteUsersByIdData,
): CancelablePromise<DeleteUsersByIdResponse> => {
  return __request(OpenAPI, {
    method: "DELETE",
    url: "/users/{id}",
    path: {
      id: data.id,
    },
    errors: {
      401: "Unauthorized - authentication required",
      403: "Forbidden - insufficient permissions",
      404: "Not found - resource does not exist",
      500: "Internal server error",
    },
  });
};

/**
 * อัปเดตข้อมูลผู้ใช้งาน
 * อัปเดตข้อมูลผู้ใช้งาน
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns User User updated successfully
 * @throws ApiError
 */
export const putUsersById = (
  data: PutUsersByIdData,
): CancelablePromise<PutUsersByIdResponse> => {
  return __request(OpenAPI, {
    method: "PUT",
    url: "/users/{id}",
    path: {
      id: data.id,
    },
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      400: "Bad request - validation errors",
      401: "Unauthorized - authentication required",
      403: "Forbidden - insufficient permissions",
      404: "Not found - resource does not exist",
      500: "Internal server error",
    },
  });
};

/**
 * รับรายการผู้ใช้งาน (เฉพาะแอดมินเท่านั้น)
 * รับรายการผู้ใช้งาน (เฉพาะแอดมินเท่านั้น)
 * @param data The data for the request.
 * @param data.page
 * @param data.limit
 * @param data.search
 * @returns unknown Users fetched successfully
 * @throws ApiError
 */
export const getUsers = (
  data: GetUsersData = {},
): CancelablePromise<GetUsersResponse> => {
  return __request(OpenAPI, {
    method: "GET",
    url: "/users",
    query: {
      page: data.page,
      limit: data.limit,
      search: data.search,
    },
    errors: {
      400: "Bad request - invalid pagination params",
      401: "Unauthorized - authentication required",
      403: "Forbidden - admin role required",
    },
  });
};

/**
 * ตั้งค่าสถานะของผู้ใช้งาน (เฉพาะแอดมินเท่านั้น)
 * ตั้งค่าสถานะของผู้ใช้งาน (เฉพาะแอดมินเท่านั้น)
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns User User status updated successfully
 * @throws ApiError
 */
export const postUsersByIdSetActive = (
  data: PostUsersByIdSetActiveData,
): CancelablePromise<PostUsersByIdSetActiveResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/users/{id}/set-active",
    path: {
      id: data.id,
    },
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      400: "Bad request - validation errors",
      401: "Unauthorized - authentication required",
      403: "Forbidden - admin role required",
      404: "User not found",
      500: "Internal server error",
    },
  });
};

/**
 * ตั้งค่าบทบาทของผู้ใช้งาน (เฉพาะแอดมินเท่านั้น)
 * ตั้งค่าบทบาทของผู้ใช้งาน (เฉพาะแอดมินเท่านั้น)
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns User User roles updated successfully
 * @throws ApiError
 */
export const postUsersByIdSetRoles = (
  data: PostUsersByIdSetRolesData,
): CancelablePromise<PostUsersByIdSetRolesResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/users/{id}/set-roles",
    path: {
      id: data.id,
    },
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      400: "Bad request - validation errors",
      401: "Unauthorized - authentication required",
      403: "Forbidden - admin role required",
      404: "User not found",
      500: "Internal server error",
    },
  });
};

/**
 * ดึงรายการผลคัดกรองทั้งหมดจากประวัติการสนทนา
 * ดึงรายการผลคัดกรองทั้งหมดจากประวัติการสนทนากับแชทบอท เรียงจากใหม่ไปเก่า
 * @returns unknown Prescreen results list
 * @throws ApiError
 */
export const getAppointmentsPrescreenResults =
  (): CancelablePromise<GetAppointmentsPrescreenResultsResponse> => {
    return __request(OpenAPI, {
      method: "GET",
      url: "/appointments/prescreen-results",
    });
  };

/**
 * ดึงข้อมูลวินิจฉัยล่าสุดจากการคัดกรองเพื่อเติมแบบฟอร์มนัดหมาย
 * ดึงข้อมูลวินิจฉัยล่าสุดจาก prescreen ที่มี diagnoses เพื่อใช้เติมแบบฟอร์มนัดหมายอัตโนมัติ
 * @returns unknown Prescreen prefill data
 * @throws ApiError
 */
export const getAppointmentsPrescreenPrefill =
  (): CancelablePromise<GetAppointmentsPrescreenPrefillResponse> => {
    return __request(OpenAPI, {
      method: "GET",
      url: "/appointments/prescreen-prefill",
      errors: {
        404: "No prescreen result with diagnoses found",
      },
    });
  };

/**
 * รับรายการทั้งหมดของโรงพยาบาล
 * รับรายการทั้งหมดของโรงพยาบาล
 * @returns unknown Paginated list of hospitals
 * @throws ApiError
 */
export const getAppointmentsHospitals =
  (): CancelablePromise<GetAppointmentsHospitalsResponse> => {
    return __request(OpenAPI, {
      method: "GET",
      url: "/appointments/hospitals",
    });
  };

/**
 * รับรายการทั้งหมดของการนัดหมาย
 * รับรายการทั้งหมดของการนัดหมาย
 * @param data The data for the request.
 * @param data.page เลขหน้า
 * @param data.limit จำนวนรายการ
 * @param data.futureOnly กรองข้อมูลเฉพาะการนัดหมายในปัจจุบันหรืออนาคต ใส่ 'true' เพื่อเปิดใช้งาน
 * @param data.historyOnly กรองข้อมูลเฉพาะการนัดหมายในอดีต ใส่ 'true' เพื่อเปิดใช้งาน
 * @returns unknown Paginated list of appointments
 * @throws ApiError
 */
export const getAppointments = (
  data: GetAppointmentsData = {},
): CancelablePromise<GetAppointmentsResponse> => {
  return __request(OpenAPI, {
    method: "GET",
    url: "/appointments",
    query: {
      page: data.page,
      limit: data.limit,
      futureOnly: data.futureOnly,
      historyOnly: data.historyOnly,
    },
  });
};

/**
 * สร้างการนัดหมายใหม่
 * สร้างการนัดหมายใหม่
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Appointment created
 * @throws ApiError
 */
export const postAppointments = (
  data: PostAppointmentsData = {},
): CancelablePromise<PostAppointmentsResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/appointments",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      400: "Bad request",
    },
  });
};

/**
 * รับข้อมูลการนัดหมายตาม ID
 * รับข้อมูลการนัดหมายตาม ID
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Appointment found
 * @throws ApiError
 */
export const getAppointmentsById = (
  data: GetAppointmentsByIdData,
): CancelablePromise<GetAppointmentsByIdResponse> => {
  return __request(OpenAPI, {
    method: "GET",
    url: "/appointments/{id}",
    path: {
      id: data.id,
    },
    errors: {
      404: "Appointment not found",
      500: "Internal server error",
    },
  });
};

/**
 * อัปเดตข้อมูลการนัดหมาย
 * อัปเดตข้อมูลการนัดหมาย
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns unknown Appointment updated
 * @throws ApiError
 */
export const putAppointmentsById = (
  data: PutAppointmentsByIdData,
): CancelablePromise<PutAppointmentsByIdResponse> => {
  return __request(OpenAPI, {
    method: "PUT",
    url: "/appointments/{id}",
    path: {
      id: data.id,
    },
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      400: "Bad request",
      404: "Appointment not found",
      500: "Internal server error",
    },
  });
};

/**
 * ลบการนัดหมาย
 * ลบการนัดหมาย
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Appointment deleted
 * @throws ApiError
 */
export const deleteAppointmentsById = (
  data: DeleteAppointmentsByIdData,
): CancelablePromise<DeleteAppointmentsByIdResponse> => {
  return __request(OpenAPI, {
    method: "DELETE",
    url: "/appointments/{id}",
    path: {
      id: data.id,
    },
    errors: {
      400: "Bad request",
      404: "Appointment not found",
    },
  });
};

/**
 * รับรายการทั้งหมดของการนัดหมาย
 * รับรายการทั้งหมดของการนัดหมาย
 * @param data The data for the request.
 * @param data.page เลขหน้า
 * @param data.limit จำนวนรายการ
 * @returns unknown Paginated list of AI appointments
 * @throws ApiError
 */
export const getLlmaasAppointments = (
  data: GetLlmaasAppointmentsData = {},
): CancelablePromise<GetLlmaasAppointmentsResponse> => {
  return __request(OpenAPI, {
    method: "GET",
    url: "/llmaas/appointments",
    query: {
      page: data.page,
      limit: data.limit,
    },
  });
};

/**
 * สร้างการนัดหมาย
 * สร้างการนัดหมาย
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Appointment created
 * @throws ApiError
 */
export const postLlmaasAppointments = (
  data: PostLlmaasAppointmentsData = {},
): CancelablePromise<PostLlmaasAppointmentsResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/llmaas/appointments",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      400: "Bad request",
    },
  });
};

/**
 * สนทนากับ AI
 * สนทนากับ AI
 * @param data The data for the request.
 * @param data.requestBody
 * @returns AIChatConversation Streaming response retrieved successfully
 * @throws ApiError
 */
export const postLlmaasChat = (
  data: PostLlmaasChatData = {},
): CancelablePromise<PostLlmaasChatResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/llmaas/chat",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      400: "Bad request - validation errors",
      401: "Unauthorized",
      429: "Too many requests - rate limit exceeded",
      500: "Internal server error",
    },
  });
};

/**
 * Send tool response from frontend
 * Send response data from frontend UI (e.g., modal form) back to waiting tool and continue LLM conversation
 * @param data The data for the request.
 * @param data.requestBody
 * @returns AIChatConversation Tool response received and LLM conversation continued
 * @throws ApiError
 */
export const postChatAiToolResponse = (
  data: PostChatAiToolResponseData = {},
): CancelablePromise<PostChatAiToolResponseResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/chat/ai/tool-response",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      400: "Bad request - validation errors",
      401: "Unauthorized",
      404: "Pending tool call not found",
      500: "Internal server error",
    },
  });
};

/**
 * สนทนากับ AI
 * สนทนากับ AI
 * @param data The data for the request.
 * @param data.requestBody
 * @returns AIChatConversation Streaming response retrieved successfully
 * @throws ApiError
 */
export const postChatAi = (
  data: PostChatAiData = {},
): CancelablePromise<PostChatAiResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/chat/ai",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      400: "Bad request - validation errors",
      401: "Unauthorized",
      429: "Too many requests - rate limit exceeded",
      500: "Internal server error",
    },
  });
};

/**
 * สร้างห้องสนทนาสำหรับผู้ใช้งาน
 * สร้างห้องสนทนาสำหรับผู้ใช้งาน
 * @param data The data for the request.
 * @param data.requestBody
 * @returns ChatRoom Chat room created successfully
 * @throws ApiError
 */
export const postChatRooms = (
  data: PostChatRoomsData = {},
): CancelablePromise<PostChatRoomsResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/chat/rooms",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      400: "Bad request - validation errors",
      401: "Unauthorized",
      500: "Internal server error",
    },
  });
};

/**
 * รับรายการห้องสนทนาของผู้ใช้งาน (เฉพาะชื่อห้องสนทนาเท่านั้น)
 * รับรายการห้องสนทนาของผู้ใช้งาน (เฉพาะชื่อห้องสนทนาเท่านั้น)
 * @returns ChatRoomsResponse Chat rooms retrieved successfully
 * @throws ApiError
 */
export const getChatRooms = (): CancelablePromise<GetChatRoomsResponse> => {
  return __request(OpenAPI, {
    method: "GET",
    url: "/chat/rooms",
    errors: {
      401: "Unauthorized",
      500: "Internal server error",
    },
  });
};

/**
 * รับรายการ pending tool calls สำหรับห้องสนทนาที่ระบุ
 * รับรายการ pending tool calls สำหรับห้องสนทนาที่ระบุ ใช้สำหรับ resume pending actions เมื่อผู้ใช้กลับมาที่ห้องสนทนา
 * @param data The data for the request.
 * @param data.id
 * @returns PendingToolCallsResponse Pending tool calls retrieved successfully
 * @throws ApiError
 */
export const getChatRoomsByIdPendingToolCalls = (
  data: GetChatRoomsByIdPendingToolCallsData,
): CancelablePromise<GetChatRoomsByIdPendingToolCallsResponse> => {
  return __request(OpenAPI, {
    method: "GET",
    url: "/chat/rooms/{id}/pending-tool-calls",
    path: {
      id: data.id,
    },
    errors: {
      401: "Unauthorized",
      403: "Forbidden - not your chat room",
      404: "Chat room not found",
      500: "Internal server error",
    },
  });
};

/**
 * รับรายการสนทนาทั้งหมดของห้องสนทนาที่ระบุ
 * รับรายการสนทนาทั้งหมดของห้องสนทนาที่ระบุ
 * @param data The data for the request.
 * @param data.id
 * @returns ChatConversationsResponse Conversations retrieved successfully
 * @throws ApiError
 */
export const getChatRoomsByIdConversations = (
  data: GetChatRoomsByIdConversationsData,
): CancelablePromise<GetChatRoomsByIdConversationsResponse> => {
  return __request(OpenAPI, {
    method: "GET",
    url: "/chat/rooms/{id}/conversations",
    path: {
      id: data.id,
    },
    errors: {
      401: "Unauthorized",
      403: "Forbidden - not your chat room",
      404: "Chat room not found",
      500: "Internal server error",
    },
  });
};

/**
 * สร้างหรืออัปเดตการสนทนา
 * สร้างหรืออัปเดตการสนทนา
 * @param data The data for the request.
 * @param data.requestBody
 * @returns SuccessResponse Conversation upserted successfully
 * @returns SuccessResponse Conversation created successfully
 * @throws ApiError
 */
export const putChatConversations = (
  data: PutChatConversationsData = {},
): CancelablePromise<PutChatConversationsResponse> => {
  return __request(OpenAPI, {
    method: "PUT",
    url: "/chat/conversations",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      400: "Bad request - validation errors",
      401: "Unauthorized",
      500: "Internal server error",
    },
  });
};

/**
 * ลบห้องสนทนาและบันทึกการสนทนาทั้งหมด
 * ลบห้องสนทนาและบันทึกการสนทนาทั้งหมด
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Chat room deleted successfully
 * @throws ApiError
 */
export const deleteChatRoomsById = (
  data: DeleteChatRoomsByIdData,
): CancelablePromise<DeleteChatRoomsByIdResponse> => {
  return __request(OpenAPI, {
    method: "DELETE",
    url: "/chat/rooms/{id}",
    path: {
      id: data.id,
    },
    errors: {
      401: "Unauthorized",
      403: "Forbidden - not your chat room",
      404: "Chat room not found",
      500: "Internal server error",
    },
  });
};

/**
 * รับสถิติของการสนทนาแบบแยกประเภท (เฉพาะแอดมินเท่านั้น)
 * บสถิติของการสนทนาแบบแยกประเภท (เฉพาะแอดมินเท่านั้น)
 * @param data The data for the request.
 * @param data.startTime เวลาเริ่มต้นตามมาตรฐาน ISO 8601 (YYYY-MM-DDTHH:mm:ss.sssZ)
 * @param data.endTime เวลาสิ้นสุดตามมาตรฐาน ISO 8601 (YYYY-MM-DDTHH:mm:ss.sssZ)
 * @returns unknown Chat conversation statistics retrieved successfully
 * @throws ApiError
 */
export const getChatConversationStats = (
  data: GetChatConversationStatsData = {},
): CancelablePromise<GetChatConversationStatsResponse> => {
  return __request(OpenAPI, {
    method: "GET",
    url: "/chat/conversation-stats",
    query: {
      startTime: data.startTime,
      endTime: data.endTime,
    },
    errors: {
      400: "Bad request - invalid date format",
      401: "Unauthorized - authentication required",
      403: "Forbidden - admin role required",
      500: "Internal server error",
    },
  });
};

/**
 * @returns unknown List of available arena model names
 * @throws ApiError
 */
export const getArenaModels = (): CancelablePromise<GetArenaModelsResponse> => {
  return __request(OpenAPI, {
    method: "GET",
    url: "/arena/models",
  });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Responses from two models
 * @throws ApiError
 */
export const postArenaAsk = (
  data: PostArenaAskData = {},
): CancelablePromise<PostArenaAskResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/arena/ask",
    body: data.requestBody,
    mediaType: "application/json",
  });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Vote recorded
 * @throws ApiError
 */
export const postArenaVote = (
  data: PostArenaVoteData = {},
): CancelablePromise<PostArenaVoteResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/arena/vote",
    body: data.requestBody,
    mediaType: "application/json",
  });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Retry failed model with SSE stream
 * @throws ApiError
 */
export const postArenaRetry = (
  data: PostArenaRetryData = {},
): CancelablePromise<PostArenaRetryResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/arena/retry",
    body: data.requestBody,
    mediaType: "application/json",
  });
};

/**
 * @returns unknown All arena votes for export
 * @throws ApiError
 */
export const getArenaExport = (): CancelablePromise<GetArenaExportResponse> => {
  return __request(OpenAPI, {
    method: "GET",
    url: "/arena/export",
  });
};

/**
 * @returns unknown Arena vote statistics
 * @throws ApiError
 */
export const getArenaStats = (): CancelablePromise<GetArenaStatsResponse> => {
  return __request(OpenAPI, {
    method: "GET",
    url: "/arena/stats",
  });
};

/**
 * @returns unknown รายการโมเดลทั้งหมด
 * @throws ApiError
 */
export const getArenaAdminModels =
  (): CancelablePromise<GetArenaAdminModelsResponse> => {
    return __request(OpenAPI, {
      method: "GET",
      url: "/arena/admin/models",
    });
  };

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown สร้างโมเดลสำเร็จ
 * @throws ApiError
 */
export const postArenaAdminModels = (
  data: PostArenaAdminModelsData = {},
): CancelablePromise<PostArenaAdminModelsResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/arena/admin/models",
    body: data.requestBody,
    mediaType: "application/json",
  });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns unknown อัปเดตโมเดลสำเร็จ
 * @throws ApiError
 */
export const putArenaAdminModelsById = (
  data: PutArenaAdminModelsByIdData,
): CancelablePromise<PutArenaAdminModelsByIdResponse> => {
  return __request(OpenAPI, {
    method: "PUT",
    url: "/arena/admin/models/{id}",
    path: {
      id: data.id,
    },
    body: data.requestBody,
    mediaType: "application/json",
  });
};

/**
 * @param data The data for the request.
 * @param data.id
 * @returns unknown ลบโมเดลสำเร็จ
 * @throws ApiError
 */
export const deleteArenaAdminModelsById = (
  data: DeleteArenaAdminModelsByIdData,
): CancelablePromise<DeleteArenaAdminModelsByIdResponse> => {
  return __request(OpenAPI, {
    method: "DELETE",
    url: "/arena/admin/models/{id}",
    path: {
      id: data.id,
    },
  });
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown ผลการทดสอบการเชื่อมต่อ
 * @throws ApiError
 */
export const postArenaAdminModelsTest = (
  data: PostArenaAdminModelsTestData = {},
): CancelablePromise<PostArenaAdminModelsTestResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/arena/admin/models/test",
    body: data.requestBody,
    mediaType: "application/json",
  });
};

/**
 * สร้างการตอบกลับสำหรับการแจ้งเตือนทางการแพทย์
 * สร้างการตอบกลับสำหรับการแจ้งเตือนทางการแพทย์
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Make response for medical reminder
 * @throws ApiError
 */
export const postMedicalRemindersResponse = (
  data: PostMedicalRemindersResponseData = {},
): CancelablePromise<PostMedicalRemindersResponseResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/medical-reminders/response",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      500: "Internal server error",
    },
  });
};

/**
 * รับรายการประวัติการแจ้งเตือนทางการแพทย์
 * รับรายการประวัติการแจ้งเตือนทางการแพทย์
 * @returns unknown List of historical medical reminders
 * @throws ApiError
 */
export const getMedicalRemindersSchedulesHistory =
  (): CancelablePromise<GetMedicalRemindersSchedulesHistoryResponse> => {
    return __request(OpenAPI, {
      method: "GET",
      url: "/medical-reminders/schedules/history",
      errors: {
        404: "Not found",
        500: "Internal server error",
      },
    });
  };

/**
 * รับรายการตาม ID ของการแจ้งเตือนทางการแพทย์
 * รับรายการตาม ID ของการแจ้งเตือนทางการแพทย์
 * @returns unknown List of upcoming medical reminders
 * @throws ApiError
 */
export const getMedicalRemindersSchedulesUpcoming =
  (): CancelablePromise<GetMedicalRemindersSchedulesUpcomingResponse> => {
    return __request(OpenAPI, {
      method: "GET",
      url: "/medical-reminders/schedules/upcoming",
      errors: {
        404: "Not found",
        500: "Internal server error",
      },
    });
  };

/**
 * รับรายการทั้งหมดของการแจ้งเตือนทางการแพทย์
 * รับรายการทั้งหมดของการแจ้งเตือนทางการแพทย์
 * @returns unknown List of medical reminders
 * @throws ApiError
 */
export const getMedicalRemindersSchedules =
  (): CancelablePromise<GetMedicalRemindersSchedulesResponse> => {
    return __request(OpenAPI, {
      method: "GET",
      url: "/medical-reminders/schedules",
      errors: {
        404: "Not found",
        500: "Internal server error",
      },
    });
  };

/**
 * สร้างการแจ้งเตือนทางการแพทย์
 * สร้างการแจ้งเตือนทางการแพทย์
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Created
 * @throws ApiError
 */
export const postMedicalRemindersSchedules = (
  data: PostMedicalRemindersSchedulesData = {},
): CancelablePromise<PostMedicalRemindersSchedulesResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/medical-reminders/schedules",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      500: "Internal server error",
    },
  });
};

/**
 * รับรายการตาม ID ของการแจ้งเตือนทางการแพทย์
 * รับรายการตาม ID ของการแจ้งเตือนทางการแพทย์
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Medical reminder info
 * @throws ApiError
 */
export const getMedicalRemindersSchedulesById = (
  data: GetMedicalRemindersSchedulesByIdData,
): CancelablePromise<GetMedicalRemindersSchedulesByIdResponse> => {
  return __request(OpenAPI, {
    method: "GET",
    url: "/medical-reminders/schedules/{id}",
    path: {
      id: data.id,
    },
    errors: {
      404: "Not found",
      500: "Internal server error",
    },
  });
};

/**
 * อัปเดตการแจ้งเตือนทางการแพทย์
 * อัปเดตการแจ้งเตือนทางการแพทย์
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns unknown Updated
 * @throws ApiError
 */
export const putMedicalRemindersSchedulesById = (
  data: PutMedicalRemindersSchedulesByIdData,
): CancelablePromise<PutMedicalRemindersSchedulesByIdResponse> => {
  return __request(OpenAPI, {
    method: "PUT",
    url: "/medical-reminders/schedules/{id}",
    path: {
      id: data.id,
    },
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      404: "Not found",
      500: "Internal server error",
    },
  });
};

/**
 * ลบการแจ้งเตือนทางการแพทย์
 * ลบการแจ้งเตือนทางการแพทย์
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Deleted
 * @throws ApiError
 */
export const deleteMedicalRemindersSchedulesById = (
  data: DeleteMedicalRemindersSchedulesByIdData,
): CancelablePromise<DeleteMedicalRemindersSchedulesByIdResponse> => {
  return __request(OpenAPI, {
    method: "DELETE",
    url: "/medical-reminders/schedules/{id}",
    path: {
      id: data.id,
    },
    errors: {
      403: "Forbidden",
      404: "Not found",
      500: "Internal server error",
    },
  });
};

/**
 * รับรายการทั้งหมดของ API key
 * รับรายการทั้งหมดของ API key
 * @param data The data for the request.
 * @param data.page
 * @param data.limit
 * @param data.sortBy
 * @param data.sortOrder
 * @returns unknown List API keys
 * @throws ApiError
 */
export const getApiKeys = (
  data: GetApiKeysData = {},
): CancelablePromise<GetApiKeysResponse> => {
  return __request(OpenAPI, {
    method: "GET",
    url: "/api-keys",
    query: {
      page: data.page,
      limit: data.limit,
      sortBy: data.sortBy,
      sortOrder: data.sortOrder,
    },
  });
};

/**
 * สร้าง API key ใหม่
 * สร้าง API key ใหม่
 * @param data The data for the request.
 * @param data.requestBody
 * @returns ApiKey Created
 * @throws ApiError
 */
export const postApiKeys = (
  data: PostApiKeysData = {},
): CancelablePromise<PostApiKeysResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/api-keys",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      400: "Bad request",
    },
  });
};

/**
 * รับข้อมูล API key ตาม ID
 * รับข้อมูล API key ตาม ID
 * @param data The data for the request.
 * @param data.id
 * @returns ApiKey Get API key
 * @throws ApiError
 */
export const getApiKeysById = (
  data: GetApiKeysByIdData,
): CancelablePromise<GetApiKeysByIdResponse> => {
  return __request(OpenAPI, {
    method: "GET",
    url: "/api-keys/{id}",
    path: {
      id: data.id,
    },
    errors: {
      404: "Not found",
    },
  });
};

/**
 * อัปเดตข้อมูล API key
 * อัปเดตข้อมูล API key
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns ApiKey Updated
 * @throws ApiError
 */
export const putApiKeysById = (
  data: PutApiKeysByIdData,
): CancelablePromise<PutApiKeysByIdResponse> => {
  return __request(OpenAPI, {
    method: "PUT",
    url: "/api-keys/{id}",
    path: {
      id: data.id,
    },
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      400: "Bad request",
      404: "Not found",
    },
  });
};

/**
 * ลบ API key
 * ลบ API key
 * @param data The data for the request.
 * @param data.id
 * @returns unknown Deleted
 * @throws ApiError
 */
export const deleteApiKeysById = (
  data: DeleteApiKeysByIdData,
): CancelablePromise<DeleteApiKeysByIdResponse> => {
  return __request(OpenAPI, {
    method: "DELETE",
    url: "/api-keys/{id}",
    path: {
      id: data.id,
    },
    errors: {
      404: "Not found",
    },
  });
};

/**
 * สร้าง API key ใหม่
 * สร้าง API key ใหม่
 * @param data The data for the request.
 * @param data.id
 * @returns ApiKey Regenerated
 * @throws ApiError
 */
export const postApiKeysByIdRegenerate = (
  data: PostApiKeysByIdRegenerateData,
): CancelablePromise<PostApiKeysByIdRegenerateResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/api-keys/{id}/regenerate",
    path: {
      id: data.id,
    },
    errors: {
      404: "Not found",
    },
  });
};

/**
 * รับรายการสมัครรับการแจ้งเตือนแบบพุช
 * รับรายการสมัครรับการแจ้งเตือนแบบพุช
 * @returns GetSubscriptionsResponse Subscriptions retrieved successfully
 * @throws ApiError
 */
export const getApiPushSubscribe =
  (): CancelablePromise<GetApiPushSubscribeResponse> => {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/push/subscribe",
      errors: {
        401: "Unauthorized",
        500: "Internal server error",
      },
    });
  };

/**
 * สมัครรับการแจ้งเตือนแบบพุช
 * สมัครรับการแจ้งเตือนแบบพุช
 * @param data The data for the request.
 * @param data.requestBody
 * @returns SubscribeResponse Subscription successful
 * @throws ApiError
 */
export const postApiPushSubscribe = (
  data: PostApiPushSubscribeData = {},
): CancelablePromise<PostApiPushSubscribeResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/api/push/subscribe",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      400: "Bad request",
      401: "Unauthorized",
    },
  });
};

/**
 * ยกเลิกการรับการแจ้งเตือนแบบพุช
 * ยกเลิกการรับการแจ้งเตือนแบบพุช
 * @param data The data for the request.
 * @param data.endpoint
 * @returns UnsubscribeResponse Unsubscription successful
 * @throws ApiError
 */
export const deleteApiPushSubscribeByEndpoint = (
  data: DeleteApiPushSubscribeByEndpointData,
): CancelablePromise<DeleteApiPushSubscribeByEndpointResponse> => {
  return __request(OpenAPI, {
    method: "DELETE",
    url: "/api/push/subscribe/{endpoint}",
    path: {
      endpoint: data.endpoint,
    },
    errors: {
      400: "Bad request",
      401: "Unauthorized",
      404: "Subscription not found or access denied",
      500: "Internal server error",
    },
  });
};

/**
 * เช็คสถานะ cron job
 * เช็คสถานะ cron job
 * @returns unknown Cron job status retrieved successfully
 * @throws ApiError
 */
export const getAdminCronStatus =
  (): CancelablePromise<GetAdminCronStatusResponse> => {
    return __request(OpenAPI, {
      method: "GET",
      url: "/admin/cron/status",
      errors: {
        500: "Internal server error",
      },
    });
  };

/**
 * สั่งทำงาน cron job สำหรับทำความสะอาดเซสชัน
 * สั่งทำงาน cron job สำหรับทำความสะอาดเซสชัน
 * @returns unknown Session cleanup triggered successfully
 * @throws ApiError
 */
export const postAdminCronCleanupSessions =
  (): CancelablePromise<PostAdminCronCleanupSessionsResponse> => {
    return __request(OpenAPI, {
      method: "POST",
      url: "/admin/cron/cleanup-sessions",
      errors: {
        400: "Bad request",
        500: "Internal server error",
      },
    });
  };

/**
 * สั่งเริ่มทำงาน cron job
 * สั่งเริ่มทำงาน cron job
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Cron task started successfully
 * @throws ApiError
 */
export const postAdminCronStartTask = (
  data: PostAdminCronStartTaskData = {},
): CancelablePromise<PostAdminCronStartTaskResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/admin/cron/start-task",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      400: "Bad request",
      500: "Internal server error",
    },
  });
};

/**
 * หยุดทำงาน cron job
 * หยุดทำงาน cron job
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Cron task stopped successfully
 * @throws ApiError
 */
export const postAdminCronStopTask = (
  data: PostAdminCronStopTaskData = {},
): CancelablePromise<PostAdminCronStopTaskResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/admin/cron/stop-task",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      400: "Bad request",
      500: "Internal server error",
    },
  });
};

/**
 * สั่ง cron job ทำงานทันที
 * สั่ง cron job ทำงานทันที
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Cron task executed successfully
 * @throws ApiError
 */
export const postAdminCronExecuteTask = (
  data: PostAdminCronExecuteTaskData = {},
): CancelablePromise<PostAdminCronExecuteTaskResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/admin/cron/execute-task",
    body: data.requestBody,
    mediaType: "application/json",
    errors: {
      400: "Bad request",
      500: "Internal server error",
    },
  });
};
